@echo off
echo ============================================
echo Starting Student Companion with Cloudflare Tunnels
echo ============================================
echo.

REM Kill existing processes
taskkill /F /IM cloudflared.exe 2>nul
taskkill /F /IM node.exe 2>nul
timeout /t 2 /nobreak >nul 2>&1

echo Starting backend server on port 3002...
start /B npm run server
timeout /t 3 /nobreak >nul 2>&1

echo Starting frontend server on port 3000...
start /B npm run dev
timeout /t 5 /nobreak >nul 2>&1

echo.
echo Starting Cloudflare tunnels...
echo.

REM Start backend tunnel and capture URL
echo Starting backend tunnel...
for /f "tokens=*" %%a in ('powershell -Command "$p = Start-Process -FilePath 'cloudflared.exe' -ArgumentList 'tunnel','--url','http://localhost:3002' -PassThru -NoNewWindow -RedirectStandardOutput 'backend-tunnel-temp.txt'; Start-Sleep -Seconds 7; Stop-Process -Id $p.Id -Force; Get-Content backend-tunnel-temp.txt | Select-String 'trycloudflare.com' | Select-Object -First 1"') do set BACKEND_LINE=%%a

REM Extract backend URL from the line
for %%i in (%BACKEND_LINE%) do (
  if "%%i"=="|" set BACKEND_URL=%%j
)

REM Better extraction using PowerShell
for /f "delims=" %%i in ('powershell -Command "Get-Content backend-tunnel-temp.txt | Select-String 'https://[^ ]+trycloudflare\.com' | Select-Object -First 1 | ForEach-Object { $_.Matches.Value }"') do set BACKEND_URL=%%i

echo Backend tunnel URL: %BACKEND_URL%

REM Update .env file with backend URL
if not "%BACKEND_URL%"=="" (
    echo Updating .env file...
    (
        echo # Backend API URL - Auto-generated by start-all.bat
        echo VITE_BACKEND_URL=%BACKEND_URL%/api
        echo.
        echo # Gemini API Key
        echo GEMINI_API_KEY=YOUR_GEMINI_API_KEY
        echo.
        echo # Database URL
        echo DATABASE_URL=postgresql://user:password@host/dbname
        echo.
        echo # Server Port
        echo PORT=3002
    ) > .env
    echo .env file updated!
) else (
    echo ERROR: Could not capture backend tunnel URL
)

echo.
echo Starting frontend tunnel...
start /B cloudflared.exe tunnel --url http://localhost:3000

echo.
echo ============================================
echo All services started!
echo ============================================
echo Frontend: http://localhost:3000
echo Backend:  http://localhost:3002
echo.
if not "%BACKEND_URL%"=="" (
    echo Backend API URL: %BACKEND_URL%
    echo.
    echo IMPORTANT: Restart frontend to apply new backend URL:
    echo   1. Press Ctrl+C in the frontend window
    echo   2. Run: npm run dev
)
echo ============================================
echo.
pause
