# Student Companion - Start All with Auto Tunnel URL Capture
# Automatically starts servers, captures tunnel URLs, updates .env, and restarts frontend

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Student Companion - Auto Tunnel Setup" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Kill existing processes
Write-Host "Stopping existing processes..." -ForegroundColor Yellow
Get-Process cloudflared -ErrorAction SilentlyContinue | Stop-Process -Force
Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 2

# Start backend server
Write-Host "Starting backend server (port 3002)..." -ForegroundColor Green
Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "npm", "run", "server" -NoNewWindow
Start-Sleep -Seconds 5

# Start frontend server  
Write-Host "Starting frontend server (port 3000)..." -ForegroundColor Green
Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "npm", "run", "dev" -NoNewWindow
Start-Sleep -Seconds 6

# Verify servers are running
Write-Host "Verifying servers..." -ForegroundColor Yellow
$port3000 = netstat -ano | Select-String ":3000.*LISTENING"
$port3002 = netstat -ano | Select-String ":3002.*LISTENING"

if ($port3000 -and $port3002) {
    Write-Host "Servers running!" -ForegroundColor Green
} else {
    Write-Host "ERROR: Servers not running!" -ForegroundColor Red
    exit 1
}

# Start backend tunnel and capture URL
Write-Host ""
Write-Host "Starting backend tunnel..." -ForegroundColor Cyan
$backendLogFile = "backend-tunnel.log"
Start-Process -FilePath "cloudflared.exe" `
    -ArgumentList "tunnel", "--url", "http://localhost:3002" `
    -NoNewWindow `
    -RedirectStandardOutput $backendLogFile

Start-Sleep -Seconds 8

# Parse backend URL
$backendLog = Get-Content $backendLogFile -Raw
$backendMatch = $backendLog | Select-String -Pattern "https://[a-zA-Z0-9-]+\.trycloudflare\.com"
$backendUrl = $backendMatch.Matches.Value

if ($backendUrl) {
    Write-Host "Backend: $backendUrl" -ForegroundColor Green
} else {
    Write-Host "WARNING: Could not capture backend URL" -ForegroundColor Yellow
    $backendUrl = "UNKNOWN"
}

# Start frontend tunnel and capture URL
Write-Host ""
Write-Host "Starting frontend tunnel..." -ForegroundColor Cyan
$frontendLogFile = "frontend-tunnel.log"
Start-Process -FilePath "cloudflared.exe" `
    -ArgumentList "tunnel", "--url", "http://localhost:3000" `
    -NoNewWindow `
    -RedirectStandardOutput $frontendLogFile

Start-Sleep -Seconds 8

# Parse frontend URL
$frontendLog = Get-Content $frontendLogFile -Raw
$frontendMatch = $frontendLog | Select-String -Pattern "https://[a-zA-Z0-9-]+\.trycloudflare\.com"
$frontendUrl = $frontendMatch.Matches.Value

if ($frontendUrl) {
    Write-Host "Frontend: $frontendUrl" -ForegroundColor Green
} else {
    Write-Host "WARNING: Could not capture frontend URL" -ForegroundColor Yellow
    $frontendUrl = "UNKNOWN"
}

# Update .env file
if ($backendUrl -ne "UNKNOWN") {
    Write-Host ""
    Write-Host "Updating .env file..." -ForegroundColor Yellow
    $envContent = @"
# Backend API URL - Auto-generated by start-all.ps1
VITE_BACKEND_URL=$backendUrl/api

# Gemini API Key
GEMINI_API_KEY=YOUR_GEMINI_API_KEY

# Database URL
DATABASE_URL=postgresql://user:password@host/dbname

# Server Port
PORT=3002
"@
    $envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline
    Write-Host ".env updated!" -ForegroundColor Green
    
    # Restart frontend to pick up new URL
    Write-Host ""
    Write-Host "Restarting frontend to apply backend URL..." -ForegroundColor Yellow
    Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Sleep -Seconds 2
    Start-Process -FilePath "cmd.exe" -ArgumentList "/c", "npm", "run", "dev" -NoNewWindow
    Start-Sleep -Seconds 5
    Write-Host "Frontend restarted!" -ForegroundColor Green
}

# Display summary
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "ALL SERVICES RUNNING!" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Local Access:" -ForegroundColor White
Write-Host "  Frontend: http://localhost:3000" -ForegroundColor Cyan
Write-Host "  Backend:  http://localhost:3002" -ForegroundColor Cyan
Write-Host ""
Write-Host "Cloudflare Tunnel Access:" -ForegroundColor White
Write-Host "  Frontend: $frontendUrl" -ForegroundColor Cyan
Write-Host "  Backend:  $backendUrl" -ForegroundColor Cyan
Write-Host ""
Write-Host "OPEN ON YOUR PHONE:" -ForegroundColor Yellow
Write-Host "  $frontendUrl" -ForegroundColor Green
Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Note: Tunnel URLs change every time you restart." -ForegroundColor Gray
Write-Host "This script auto-captures them for you." -ForegroundColor Gray
Write-Host ""
Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
